/**
 * Loading Google Fonts families from the CDN.
 *
 * The font files are **never bundled**: this module builds the official
 * `css2` URL and injects the `<link>` tags into the document — preconnects
 * included. The browser then downloads the weights actually used, as WOFF2
 * sliced by Unicode range, from the Google CDN. This is the lightest path: a
 * few hundred bytes of CSS on the application side, the rest in a shared
 * cache.
 *
 * The {@link GOOGLE_FONTS} registry lists the most used families so as to
 * offer autocompletion and the right fallback stack; **any** family of the
 * Google Fonts catalog is still accepted as a free-form string.
 *
 * @example
 * import { loadGoogleFonts, applyFontFamily } from '@odoro-cli/libs/styles'
 *
 * loadGoogleFonts([
 *   { family: 'Inter', weights: [400, 500, 700] },
 *   { family: 'JetBrains Mono' },
 * ])
 * applyFontFamily('sans', 'Inter')
 *
 * @module
 */

/** Typographic category of a family, as the Google Fonts catalog means it. */
export type GoogleFontCategory =
  'sans-serif' | 'serif' | 'display' | 'handwriting' | 'monospace'

/**
 * Listed families of the Google Fonts catalog, with their category.
 *
 * The category decides the fallback stack generated by {@link fontStack}: the
 * text stays readable while loading, and stays so if the CDN is unreachable.
 */
export const GOOGLE_FONTS = {
  // Sans-serif.
  Inter: 'sans-serif',
  Roboto: 'sans-serif',
  'Open Sans': 'sans-serif',
  Lato: 'sans-serif',
  Montserrat: 'sans-serif',
  Poppins: 'sans-serif',
  Nunito: 'sans-serif',
  'Nunito Sans': 'sans-serif',
  Raleway: 'sans-serif',
  'Work Sans': 'sans-serif',
  Rubik: 'sans-serif',
  'DM Sans': 'sans-serif',
  Manrope: 'sans-serif',
  Outfit: 'sans-serif',
  Sora: 'sans-serif',
  Figtree: 'sans-serif',
  Karla: 'sans-serif',
  Mulish: 'sans-serif',
  Urbanist: 'sans-serif',
  Barlow: 'sans-serif',
  Cabin: 'sans-serif',
  'Josefin Sans': 'sans-serif',
  Quicksand: 'sans-serif',
  Lexend: 'sans-serif',
  'Plus Jakarta Sans': 'sans-serif',
  'Public Sans': 'sans-serif',
  'Space Grotesk': 'sans-serif',
  'IBM Plex Sans': 'sans-serif',
  'Source Sans 3': 'sans-serif',
  'Noto Sans': 'sans-serif',
  'PT Sans': 'sans-serif',
  Oswald: 'sans-serif',
  Archivo: 'sans-serif',
  'Exo 2': 'sans-serif',
  Chivo: 'sans-serif',
  Heebo: 'sans-serif',
  Assistant: 'sans-serif',
  Jost: 'sans-serif',
  Kanit: 'sans-serif',
  Onest: 'sans-serif',
  'Albert Sans': 'sans-serif',
  'Instrument Sans': 'sans-serif',
  'Schibsted Grotesk': 'sans-serif',
  // Serif.
  'Playfair Display': 'serif',
  Merriweather: 'serif',
  Lora: 'serif',
  'PT Serif': 'serif',
  'Crimson Text': 'serif',
  'Libre Baskerville': 'serif',
  'EB Garamond': 'serif',
  'Cormorant Garamond': 'serif',
  Bitter: 'serif',
  'Source Serif 4': 'serif',
  'Noto Serif': 'serif',
  'DM Serif Display': 'serif',
  Fraunces: 'serif',
  Spectral: 'serif',
  Literata: 'serif',
  'Zilla Slab': 'serif',
  'Roboto Slab': 'serif',
  Arvo: 'serif',
  'Instrument Serif': 'serif',
  // Monospace.
  'JetBrains Mono': 'monospace',
  'Fira Code': 'monospace',
  'Source Code Pro': 'monospace',
  'IBM Plex Mono': 'monospace',
  'Roboto Mono': 'monospace',
  'Space Mono': 'monospace',
  'Ubuntu Mono': 'monospace',
  Inconsolata: 'monospace',
  'DM Mono': 'monospace',
  'Overpass Mono': 'monospace',
  'Geist Mono': 'monospace',
  // Display.
  'Bebas Neue': 'display',
  Anton: 'display',
  Righteous: 'display',
  'Alfa Slab One': 'display',
  'Abril Fatface': 'display',
  Comfortaa: 'display',
  Fredoka: 'display',
  'Baloo 2': 'display',
  'Titan One': 'display',
  Bungee: 'display',
  Orbitron: 'display',
  'Press Start 2P': 'display',
  Silkscreen: 'display',
  VT323: 'display',
  Audiowide: 'display',
  Monoton: 'display',
  Lobster: 'display',
  // Handwriting.
  Pacifico: 'handwriting',
  'Dancing Script': 'handwriting',
  Caveat: 'handwriting',
  Satisfy: 'handwriting',
  'Great Vibes': 'handwriting',
  'Amatic SC': 'handwriting',
  'Shadows Into Light': 'handwriting',
  'Indie Flower': 'handwriting',
  'Permanent Marker': 'handwriting',
} as const satisfies Record<string, GoogleFontCategory>

/** Name of a listed family. */
export type GoogleFontName = keyof typeof GOOGLE_FONTS

/**
 * Family accepted by the module: a listed family, or any name of the Google
 * Fonts catalog as a free-form string. The union with `string` preserves
 * autocompletion of the known families.
 */
export type GoogleFontFamily = GoogleFontName | (string & Record<never, never>)

/** Request to load a family. */
export interface GoogleFontRequest {
  /** Name of the family, as it appears in the catalog. */
  family: GoogleFontFamily
  /** Weights to load. @defaultValue [400, 700] */
  weights?: readonly number[]
  /** Also loads the italics of the requested weights. @defaultValue false */
  italics?: boolean
}

/** A bare family counts as a request with the default settings. */
export type GoogleFontInput = GoogleFontFamily | GoogleFontRequest

/** Options of {@link loadGoogleFonts} and {@link googleFontsUrl}. */
export interface GoogleFontsOptions {
  /**
   * `font-display` strategy. `swap` shows the text immediately in the
   * fallback font, then swaps.
   *
   * @defaultValue 'swap'
   */
  display?: 'auto' | 'block' | 'swap' | 'fallback' | 'optional'
}

/** Fallback stacks per category, aligned on the families of the foundation. */
const FALLBACKS: Readonly<Record<GoogleFontCategory, string>> = {
  'sans-serif':
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
  serif: "ui-serif, Georgia, Cambria, 'Times New Roman', Times, serif",
  display:
    "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
  handwriting: 'cursive',
  monospace:
    "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', monospace",
}

/** Normalizes an input into a complete request. */
function toRequest(input: GoogleFontInput): Required<GoogleFontRequest> {
  const request = typeof input === 'string' ? { family: input } : input
  return {
    family: request.family,
    weights: request.weights ?? [400, 700],
    italics: request.italics ?? false,
  }
}

/** The `family=` chunk of the `css2` URL for one request. */
function familyParam({ family, weights, italics }: Required<GoogleFontRequest>): string {
  const name = family.trim().replace(/ /g, '+')
  const sorted = [...new Set(weights)].sort((a, b) => a - b)

  // The css2 API requires sorted tuples: first all the romans, then all the
  // italics, each group by ascending weight.
  const axis = italics
    ? `ital,wght@${[
        ...sorted.map((weight) => `0,${weight}`),
        ...sorted.map((weight) => `1,${weight}`),
      ].join(';')}`
    : `wght@${sorted.join(';')}`

  return `family=${name}:${axis}`
}

/**
 * Builds the Google Fonts stylesheet URL for a set of families.
 *
 * @example
 * googleFontsUrl(['Inter', { family: 'Lora', weights: [400], italics: true }])
 * // 'https://fonts.googleapis.com/css2?family=Inter:wght@400;700&family=Lora:ital,wght@0,400;1,400&display=swap'
 */
export function googleFontsUrl(
  fonts: readonly GoogleFontInput[],
  options: GoogleFontsOptions = {},
): string {
  if (fonts.length === 0) {
    throw new Error('[odoro/styles] googleFontsUrl() requires at least one family.')
  }
  const params = fonts.map((input) => familyParam(toRequest(input)))
  return `https://fonts.googleapis.com/css2?${params.join('&')}&display=${options.display ?? 'swap'}`
}

/** Marker set on the injected tags, for idempotence and removal. */
const LINK_MARKER = 'data-odoro-fonts'

/**
 * Injects into `<head>` the loading tags of a set of families: the two
 * preconnects to the CDN, then the `css2` stylesheet.
 *
 * Idempotent: a URL already present is not injected twice. Without a DOM
 * (server rendering), the function does nothing.
 *
 * @returns A function removing the injected stylesheet — the preconnects,
 *   shared between all calls, stay in place.
 *
 * @example
 * loadGoogleFonts([{ family: 'Poppins', weights: [400, 600, 800] }])
 */
export function loadGoogleFonts(
  fonts: readonly GoogleFontInput[],
  options: GoogleFontsOptions = {},
): () => void {
  if (typeof document === 'undefined') return () => undefined

  const head = document.head

  for (const [href, crossOrigin] of [
    ['https://fonts.googleapis.com', false],
    ['https://fonts.gstatic.com', true],
  ] as const) {
    if (head.querySelector(`link[rel="preconnect"][href="${href}"]`) !== null) continue
    const preconnect = document.createElement('link')
    preconnect.rel = 'preconnect'
    preconnect.href = href
    if (crossOrigin) preconnect.crossOrigin = 'anonymous'
    preconnect.setAttribute(LINK_MARKER, '')
    head.appendChild(preconnect)
  }

  const url = googleFontsUrl(fonts, options)
  const existing = head.querySelector<HTMLLinkElement>(
    `link[rel="stylesheet"][href="${url}"]`,
  )
  if (existing !== null) return () => existing.remove()

  const stylesheet = document.createElement('link')
  stylesheet.rel = 'stylesheet'
  stylesheet.href = url
  stylesheet.setAttribute(LINK_MARKER, '')
  head.appendChild(stylesheet)

  return () => stylesheet.remove()
}

/**
 * Complete `font-family` stack for a family: the family, then the fallback
 * stack of its category.
 *
 * @param category Category of the family. Inferred from the registry for a
 *   listed family; `sans-serif` otherwise.
 *
 * @example
 * fontStack('Fira Code') // "'Fira Code', ui-monospace, ..., monospace"
 */
export function fontStack(
  family: GoogleFontFamily,
  category?: GoogleFontCategory,
): string {
  const resolved =
    category ??
    (family in GOOGLE_FONTS ? GOOGLE_FONTS[family as GoogleFontName] : 'sans-serif')
  return `'${family}', ${FALLBACKS[resolved]}`
}

/**
 * Points a font family of the style system (`--o-font-*`) at a loaded family,
 * fallback stack included. Everything using `o-font-sans`, `o-font-serif` or
 * `o-font-mono` — the page body first of all — switches immediately.
 *
 * @example
 * loadGoogleFonts(['Sora'])
 * applyFontFamily('sans', 'Sora')
 */
export function applyFontFamily(
  slot: 'sans' | 'serif' | 'mono',
  family: GoogleFontFamily,
  category?: GoogleFontCategory,
): void {
  if (typeof document === 'undefined') return
  document.documentElement.style.setProperty(
    `--o-font-${slot}`,
    fontStack(family, category),
  )
}
