/**
 * La table de `atelier`.
 *
 * Les renommages sont derives du bloc de jetons de la feuille par
 * `scripts/derive-template-classes.mjs` ; ce qui suit est ce qu il ne peut pas
 * deviner.
 */

export const RENAMED = {
  /*
   * Trois homonymes. Notre systeme connait `o-font-sans`, `o-font-serif` et
   * `o-ease-entrance`, et n entend pas la meme chose : ici la sans-serif est
   * la Mulish, la serif est l Instrument Serif, et la courbe est celle du
   * gabarit.
   *
   * Une subtilite s ajoute : ces jetons sont lies dans un bloc `@theme inline`,
   * qui substitue la valeur dans les **utilitaires** sans emettre la variable.
   * `var(--font-sans)` dans une regle d auteur ne resout rien, mais la classe
   * `font-sans`, elle, vit — et vaut bien la Mulish.
   */
  "font-sans": "at-font-sans",
  "font-serif": "at-font-serif",
  "ease-entrance": "at-ease-entrance",
  "bg-linear-to-b": "at-bg-linear-to-b",
  "bg-linear-to-t": "at-bg-linear-to-t",
  "data-[on=true]:bg-accent": "at-data-on-true-bg-accent",
  "data-[on=true]:w-6": "at-data-on-true-w-6",
  "data-drag:cursor-grabbing": "at-data-drag-cursor-grabbing",
  "from-background": "at-from-background",
  "from-background/85": "at-from-background-85",
  "from-foreground/85": "at-from-foreground-85",
  "in-data-front:shadow-[0_40px_90px_-20px_var(--tw-shadow-color)]": "at-in-data-front-shadow-0-40px-90px-20px-var-tw-shadow-color",
  "shadow-foreground/40": "at-shadow-foreground-40",
  "stacked:order-1": "at-stacked-order-1",
  "stacked:order-2": "at-stacked-order-2",
  "to-55%": "at-to-55",
  "to-surface-raised": "at-to-surface-raised",
  "transform-3d": "at-transform-3d",
  "via-30%": "at-via-30",
  "via-background/30": "at-via-background-30",
  "via-foreground/25": "at-via-foreground-25",
  "-mb-[0.16em]": "at--mb-0-16em",
  "-mb-[0.18em]": "at--mb-0-18em",
  "-mx-frame-gutter": "at--mx-frame-gutter",
  "-my-[0.15em]": "at--my-0-15em",
  "-rotate-90": "at--rotate-90",
  "-translate-x-1/2": "at--translate-x-1-2",
  "-translate-y-1/2": "at--translate-y-1-2",
  "after:bg-line/20": "at-after-bg-line-20",
  "after:h-px": "at-after-h-px",
  "after:w-6": "at-after-w-6",
  "aspect-[4/5]": "at-aspect-4-5",
  "backface-hidden": "at-backface-hidden",
  "before:bg-line/20": "at-before-bg-line-20",
  "before:h-px": "at-before-h-px",
  "before:w-6": "at-before-w-6",
  "bg-accent": "at-bg-accent",
  "bg-background": "at-bg-background",
  "bg-background/60": "at-bg-background-60",
  "bg-background/95": "at-bg-background-95",
  "bg-black/40": "at-bg-black-40",
  "bg-foreground": "at-bg-foreground",
  "bg-foreground/10": "at-bg-foreground-10",
  "bg-foreground/15": "at-bg-foreground-15",
  "bg-line/30": "at-bg-line-30",
  "bg-surface-raised": "at-bg-surface-raised",
  "border-accent-foreground/20": "at-border-accent-foreground-20",
  "border-foreground/10": "at-border-foreground-10",
  "border-foreground/15": "at-border-foreground-15",
  "border-line/10": "at-border-line-10",
  "border-line/15": "at-border-line-15",
  "bottom-[calc(100%+0.75rem)]": "at-bottom-calc-100-0-75rem",
  "bottom-[clamp(124px,17vh,156px)]": "at-bottom-clamp-124px-17vh-156px",
  "bottom-frame-gutter": "at-bottom-frame-gutter",
  "col-start-9": "at-col-start-9",
  "duration-[var(--duration-fast)]": "at-duration-var-duration-fast",
  "duration-[var(--duration-normal)]": "at-duration-var-duration-normal",
  "duration-[var(--duration-slow)]": "at-duration-var-duration-slow",
  "focus-visible:outline-2": "at-focus-visible-outline-2",
  "focus-visible:outline-foreground": "at-focus-visible-outline-foreground",
  "focus-visible:outline-offset-2": "at-focus-visible-outline-offset-2",
  "font-display": "at-font-display",
  "gap-[0.1389vw]": "at-gap-0-1389vw",
  "gap-[0.22rem]": "at-gap-0-22rem",
  "gap-[1.2vw]": "at-gap-1-2vw",
  "gap-[1vw]": "at-gap-1vw",
  "gap-[7px]": "at-gap-7px",
  "gap-[max(12px,2.2222vw)]": "at-gap-max-12px-2-2222vw",
  "gap-[max(18px,2.2vw)]": "at-gap-max-18px-2-2vw",
  "gap-x-[2vw]": "at-gap-x-2vw",
  "gap-y-[4vw]": "at-gap-y-4vw",
  "grid-cols-[1fr_auto_1fr]": "at-grid-cols-1fr-auto-1fr",
  "group-hover:opacity-100": "at-group-hover-opacity-100",
  "h-[18px]": "at-h-18px",
  "h-[26vh]": "at-h-26vh",
  "h-[46%]": "at-h-46",
  "h-[max(40px,2.6vw)]": "at-h-max-40px-2-6vw",
  "h-frame-control": "at-h-frame-control",
  "h-lvh": "at-h-lvh",
  "hover:bg-foreground": "at-hover-bg-foreground",
  "hover:bg-foreground/5": "at-hover-bg-foreground-5",
  "hover:border-foreground": "at-hover-border-foreground",
  "hover:scale-[1.05]": "at-hover-scale-1-05",
  "hover:text-background": "at-hover-text-background",
  "hover:text-foreground/70": "at-hover-text-foreground-70",
  "inset-x-3.5": "at-inset-x-3-5",
  "leading-[0.82]": "at-leading-0-82",
  "leading-[0.8]": "at-leading-0-8",
  "leading-[0.95]": "at-leading-0-95",
  "leading-[0.9]": "at-leading-0-9",
  "leading-[1.05]": "at-leading-1-05",
  "leading-[1.15]": "at-leading-1-15",
  "leading-[1.22]": "at-leading-1-22",
  "leading-[1.5]": "at-leading-1-5",
  "leading-display": "at-leading-display",
  "leading-none": "at-leading-none",
  "left-[3px]": "at-left-3px",
  "left-[clamp(22px,3.4vw,40px)]": "at-left-clamp-22px-3-4vw-40px",
  "max-h-[calc(100dvh-1.5rem)]": "at-max-h-calc-100dvh-1-5rem",
  "max-w-[26ch]": "at-max-w-26ch",
  "max-w-[28ch]": "at-max-w-28ch",
  "max-w-[30ch]": "at-max-w-30ch",
  "max-w-[34ch]": "at-max-w-34ch",
  "max-w-[38rem]": "at-max-w-38rem",
  "max-w-[560px]": "at-max-w-560px",
  "max-w-[64vw]": "at-max-w-64vw",
  "ml-[8.3vw]": "at-ml-8-3vw",
  "mt-[0.8vw]": "at-mt-0-8vw",
  "mt-[1.4vw]": "at-mt-1-4vw",
  "mt-[1.6vw]": "at-mt-1-6vw",
  "mt-[2.4vw]": "at-mt-2-4vw",
  "mt-[2vw]": "at-mt-2vw",
  "mt-[3vw]": "at-mt-3vw",
  "mt-[5vw]": "at-mt-5vw",
  "mt-[6vw]": "at-mt-6vw",
  "overflow-x-clip": "at-overflow-x-clip",
  "pb-[9vw]": "at-pb-9vw",
  "pb-[calc(var(--frame-gutter)+var(--frame-control)+4lvh)]": "at-pb-calc-var-frame-gutter-var-frame-control-4lvh",
  "pb-[clamp(22px,4vh,40px)]": "at-pb-clamp-22px-4vh-40px",
  "pt-[8vw]": "at-pt-8vw",
  "pt-[max(96px,8vw)]": "at-pt-max-96px-8vw",
  "px-[max(16px,3.3333vw)]": "at-px-max-16px-3-3333vw",
  "px-[max(24px,2.8vw)]": "at-px-max-24px-2-8vw",
  "px-[max(24px,3.3333vw)]": "at-px-max-24px-3-3333vw",
  "px-frame-gutter": "at-px-frame-gutter",
  "py-[0.15em]": "at-py-0-15em",
  "py-[12lvh]": "at-py-12lvh",
  "py-[16lvh]": "at-py-16lvh",
  "py-[max(18px,1.4vw)]": "at-py-max-18px-1-4vw",
  "py-frame-gutter": "at-py-frame-gutter",
  "right-[clamp(22px,3.4vw,40px)]": "at-right-clamp-22px-3-4vw-40px",
  "rounded-[10px]": "at-rounded-10px",
  "rounded-[50%]": "at-rounded-50",
  "rounded-card": "at-rounded-card",
  "shadow": "at-shadow",
  "shadow-[0_26px_60px_-18px_var(--tw-shadow-color)]": "at-shadow-0-26px-60px-18px-var-tw-shadow-color",
  "size-frame-control": "at-size-frame-control",
  "sm:w-[420px]": "at-sm-w-420px",
  "stacked:block": "at-stacked-block",
  "stacked:col-span-1": "at-stacked-col-span-1",
  "stacked:col-span-2": "at-stacked-col-span-2",
  "stacked:flex": "at-stacked-flex",
  "stacked:flex-1": "at-stacked-flex-1",
  "stacked:flex-col": "at-stacked-flex-col",
  "stacked:gap-2": "at-stacked-gap-2",
  "stacked:gap-3": "at-stacked-gap-3",
  "stacked:gap-4": "at-stacked-gap-4",
  "stacked:gap-6": "at-stacked-gap-6",
  "stacked:gap-x-6": "at-stacked-gap-x-6",
  "stacked:gap-y-10": "at-stacked-gap-y-10",
  "stacked:grid-cols-2": "at-stacked-grid-cols-2",
  "stacked:grid-cols-[auto_1fr_auto]": "at-stacked-grid-cols-auto-1fr-auto",
  "stacked:hidden": "at-stacked-hidden",
  "stacked:items-center": "at-stacked-items-center",
  "stacked:items-start": "at-stacked-items-start",
  "stacked:justify-end": "at-stacked-justify-end",
  "stacked:justify-start": "at-stacked-justify-start",
  "stacked:max-w-none": "at-stacked-max-w-none",
  "stacked:ml-0": "at-stacked-ml-0",
  "stacked:mt-12": "at-stacked-mt-12",
  "stacked:mt-14": "at-stacked-mt-14",
  "stacked:mt-2": "at-stacked-mt-2",
  "stacked:mt-4": "at-stacked-mt-4",
  "stacked:mt-5": "at-stacked-mt-5",
  "stacked:mt-6": "at-stacked-mt-6",
  "stacked:mt-8": "at-stacked-mt-8",
  "stacked:pb-0": "at-stacked-pb-0",
  "stacked:pb-[10lvh]": "at-stacked-pb-10lvh",
  "stacked:pt-16": "at-stacked-pt-16",
  "stacked:pt-[max(112px,24lvh)]": "at-stacked-pt-max-112px-24lvh",
  "stacked:py-[14lvh]": "at-stacked-py-14lvh",
  "stacked:self-start": "at-stacked-self-start",
  "stacked:size-11": "at-stacked-size-11",
  "stacked:text-[1.5rem]": "at-stacked-text-1-5rem",
  "stacked:text-[10vw]": "at-stacked-text-10vw",
  "stacked:text-[11vw]": "at-stacked-text-11vw",
  "stacked:text-[13vw]": "at-stacked-text-13vw",
  "stacked:text-[26vw]": "at-stacked-text-26vw",
  "stacked:text-[30vh]": "at-stacked-text-30vh",
  "stacked:text-[7.6vw]": "at-stacked-text-7-6vw",
  "stacked:text-[9vw]": "at-stacked-text-9vw",
  "stacked:text-left": "at-stacked-text-left",
  "text-[1.75rem]": "at-text-1-75rem",
  "text-[18.5vw]": "at-text-18-5vw",
  "text-[19px]": "at-text-19px",
  "text-[2.1rem]": "at-text-2-1rem",
  "text-[2.2rem]": "at-text-2-2rem",
  "text-[22vw]": "at-text-22vw",
  "text-[27vw]": "at-text-27vw",
  "text-[3.4vw]": "at-text-3-4vw",
  "text-[4.6vw]": "at-text-4-6vw",
  "text-[42vh]": "at-text-42vh",
  "text-[5.6vw]": "at-text-5-6vw",
  "text-[7vw]": "at-text-7vw",
  "text-[clamp(22px,2.8vw,34px)]": "at-text-clamp-22px-2-8vw-34px",
  "text-[max(15px,1.2vw)]": "at-text-max-15px-1-2vw",
  "text-accent-foreground": "at-text-accent-foreground",
  "text-accent-foreground/10": "at-text-accent-foreground-10",
  "text-accent-foreground/70": "at-text-accent-foreground-70",
  "text-accent-foreground/80": "at-text-accent-foreground-80",
  "text-background": "at-text-background",
  "text-background/90": "at-text-background-90",
  "text-foreground": "at-text-foreground",
  "text-foreground-muted": "at-text-foreground-muted",
  "text-foreground-muted/60": "at-text-foreground-muted-60",
  "text-foreground-muted/70": "at-text-foreground-muted-70",
  "text-foreground-muted/80": "at-text-foreground-muted-80",
  "text-foreground/40": "at-text-foreground-40",
  "text-foreground/60": "at-text-foreground-60",
  "text-foreground/70": "at-text-foreground-70",
  "text-foreground/[0.045]": "at-text-foreground-0-045",
  "text-frame-body": "at-text-frame-body",
  "text-frame-caption": "at-text-frame-caption",
  "text-frame-figure": "at-text-frame-figure",
  "text-frame-lead": "at-text-frame-lead",
  "text-frame-nav": "at-text-frame-nav",
  "top-[3px]": "at-top-3px",
  "top-[51%]": "at-top-51",
  "top-[68%]": "at-top-68",
  "top-[max(80px,13vh)]": "at-top-max-80px-13vh",
  "tracking-[-0.018em]": "at-tracking-0-018em",
  "tracking-[-0.01em]": "at-tracking-0-01em",
  "tracking-[-0.025em]": "at-tracking-0-025em",
  "tracking-[-0.02em]": "at-tracking-0-02em",
  "tracking-[-0.035em]": "at-tracking-0-035em",
  "tracking-[-0.03em]": "at-tracking-0-03em",
  "tracking-[0.04em]": "at-tracking-0-04em",
  "tracking-[0.12em]": "at-tracking-0-12em",
  "tracking-[0.16em]": "at-tracking-0-16em",
  "tracking-[0.24em]": "at-tracking-0-24em",
  "tracking-[0.26em]": "at-tracking-0-26em",
  "tracking-[0.28em]": "at-tracking-0-28em",
  "tracking-[0.2em]": "at-tracking-0-2em",
  "tracking-[0.3em]": "at-tracking-0-3em",
  "transition-[width,background-color]": "at-transition-width-background-color",
  "w-[18px]": "at-w-18px",
  "w-[3vw]": "at-w-3vw",
  "w-[62vw]": "at-w-62vw",
  "w-[calc(100vw-1.5rem)]": "at-w-calc-100vw-1-5rem",
  "z-1": "at-z-1",
  "z-2": "at-z-2",
  "z-60": "at-z-60",
  "z-[100]": "at-z-100",
}

export const UNCHANGED = new Set([
  /*
   * `group` n a pas de regle a lui : c est la marque que les selecteurs
   * `.group:hover .x` vont chercher. Les deux autres sont les prises auxquelles
   * le defilement doux s accroche depuis le script.
   */
  'group',
  'scroll-layout',
  'scroll-layout-content',
])

export const FAUX_AMIS = new Set([
  /*
   * Huit mots verifies un a un : des valeurs CSS ecrites en clair
   * (`visibility: hidden|visible`, `position: relative|sticky`), un nom
   * d evenement, et de la prose de commentaire qui cite une classe sans en
   * etre une.
   */
  'hidden',
  'visible',
  'pointer-events-auto',
  'pointer-events-none',
  'relative',
  'sticky',
  'resize',
  'z-50',
])

export const IGNORED = new Set(FAUX_AMIS)

export const RESPELLED = { border: 'o-border-w-1' }
