/**
 * La table de classes du gabarit `helion`.
 *
 * Trois cent quatre-vingt-seize noms, dont trois cent quatre-vingt-cinq
 * derives par `scripts/derive-template-classes.mjs` a partir du bloc `@theme`
 * du gabarit, de ses `@custom-variant` et de l echelle d espacement de l autre
 * moteur. Onze demandaient une decision.
 *
 * Ce gabarit se donne sept ruptures a lui — `hero-lg`, `hero-md`, `hero-sm`,
 * `hero-xs`, `pad-md`, `pad-sm`, `menu` — et deux variantes de hauteur,
 * `max-h-828` et `max-h-717`. Aucune n existe chez nous : toutes les classes
 * qui les portent sont donc des classes du gabarit.
 *
 * @module
 */

/** Les noms derives, plus les quelques-uns nommes a la main. */
export const RENAMED = {
  // Homonyme. Notre `o-font-sans` designe notre pile ; ici la famille est
  // Gilroy. Prefixee, elle changeait la police sans qu un nom bouge.
  'font-sans': 'hl-font-sans',
  'text-foreground/92': 'hl-text-foreground-92',
  'text-sm/[1.55]': 'hl-text-sm-1-55',
  'text-white/45': 'hl-text-white-45',
  'text-white/50': 'hl-text-white-50',
  'text-white/60': 'hl-text-white-60',
  'text-white/70': 'hl-text-white-70',
  'text-white/80': 'hl-text-white-80',
  'text-white/90': 'hl-text-white-90',
  'text-xs/[1.4]': 'hl-text-xs-1-4',
  'text-xs/none': 'hl-text-xs-none',
  'top-[100px]': 'hl-top-100px',
  'top-[3.25rem]': 'hl-top-3-25rem',
  'top-[360px]': 'hl-top-360px',
  'top-[3px]': 'hl-top-3px',
  'top-[633px]': 'hl-top-633px',
  'top-[703px]': 'hl-top-703px',
  'top-[712px]': 'hl-top-712px',
  'top-[calc(100%+10px)]': "hl-top-calc-100-10px",
  'tracking-[-0.01em]': 'hl-tracking-0-01em',
  'tracking-[-0.02em]': 'hl-tracking-0-02em',
  'tracking-[0.005em]': 'hl-tracking-0-005em',
  'tracking-[0.01em]': 'hl-tracking-0-01em',
  'tracking-[0.02em]': 'hl-tracking-0-02em',
  'tracking-[0.03em]': 'hl-tracking-0-03em',
  'tracking-[0.04em]': 'hl-tracking-0-04em',
  'tracking-[0.12em]': 'hl-tracking-0-12em',
  'tracking-[0.14em]': 'hl-tracking-0-14em',
  'tracking-[0.15em]': 'hl-tracking-0-15em',
  'tracking-[0.1em]': 'hl-tracking-0-1em',
  'tracking-[0.22em]': 'hl-tracking-0-22em',
  'tracking-[0.24em]': 'hl-tracking-0-24em',
  'tracking-[0.28em]': 'hl-tracking-0-28em',
  'tracking-[0.34em]': 'hl-tracking-0-34em',
  'tracking-[0.3em]': 'hl-tracking-0-3em',
  'transform-gpu': 'hl-transform-gpu',
  'w-[0.75rem]': 'hl-w-0-75rem',
  'w-[1.125rem]': 'hl-w-1-125rem',
  'w-[123.86px]': 'hl-w-123-86px',
  'w-[1440px]': 'hl-w-1440px',
  'w-[180px]': 'hl-w-180px',
  'w-[18px]': 'hl-w-18px',
  'w-[220px]': 'hl-w-220px',
  'w-[300px]': 'hl-w-300px',
  'w-[400px]': 'hl-w-400px',
  'w-[405px]': 'hl-w-405px',
  'w-[423px]': 'hl-w-423px',
  'w-[623px]': 'hl-w-623px',
  'w-[663px]': 'hl-w-663px',
  'w-[calc(100vw-1.5rem)]': "hl-w-calc-100vw-1-5rem",
  'w-[min(100%,var(--container-max))]': 'hl-w-min-100-var-container-max',
  'w-[min(20rem,56vw)]': 'hl-w-min-20rem-56vw',
  'w-lvw': 'hl-w-lvw',
  'z-[100]': 'hl-z-100',
  'z-[120]': 'hl-z-120',
  'z-[200]': 'hl-z-200',
  'z-[2]': 'hl-z-2',
  // Une propriete arbitraire, ecrite telle quelle par l original.
  '[-webkit-background-clip:text]': 'hl-clip-texte',
  // Une couleur d anneau avec son opacite.
  'ring-accent-500/30': 'hl-anneau-accent',
  // Une taille livree, avec un interligne arbitraire.
  'text-base/[1.7]': 'hl-fs-base-17',
  '!rounded-[24px]': "hl--rounded-24px",
  '-ml-[0.375rem]': 'hl-ml-0-375rem',
  '-ml-[0.5625rem]': 'hl-ml-0-5625rem',
  '-translate-x-1/2': 'hl-translate-x-1-2',
  '-translate-y-1/2': 'hl-translate-y-1-2',
  '-z-10': 'hl-z-10',
  'accent-[#6d8bff]': 'hl-accent-6d8bff',
  'active:bg-foreground/10': 'hl-active-bg-foreground-10',
  'backdrop-blur-[30px]': 'hl-backdrop-blur-30px',
  'backdrop-blur-[8px]': 'hl-backdrop-blur-8px',
  'backdrop-saturate-[1.4]': 'hl-backdrop-saturate-1-4',
  'backface-hidden': 'hl-backface-hidden',
  'bg-[#3a5cff]/20': 'hl-bg-3a5cff-20',
  'bg-[#3a5cff]/30': 'hl-bg-3a5cff-30',
  'bg-[color:var(--timeline-rail)]': 'hl-bg-color-var-timeline-rail',
  'bg-[image:var(--gradient-burger-glow)]': 'hl-bg-image-var-gradient-burger-glow',
  'bg-[image:var(--gradient-footer)]': 'hl-bg-image-var-gradient-footer',
  'bg-[image:var(--gradient-footer-rule)]': 'hl-bg-image-var-gradient-footer-rule',
  'bg-[image:var(--gradient-hero-icon)]': 'hl-bg-image-var-gradient-hero-icon',
  'bg-[var(--hero-glass)]': 'hl-bg-var-hero-glass',
  'bg-accent-300': 'hl-bg-accent-300',
  'bg-accent-500': 'hl-bg-accent-500',
  'bg-accent-500/12': 'hl-bg-accent-500-12',
  'bg-accent-500/14': 'hl-bg-accent-500-14',
  'bg-accent-500/16': 'hl-bg-accent-500-16',
  'bg-accent-500/20': 'hl-bg-accent-500-20',
  'bg-accent-500/6': 'hl-bg-accent-500-6',
  'bg-accent-500/8': 'hl-bg-accent-500-8',
  'bg-accent-500/80': 'hl-bg-accent-500-80',
  'bg-background': 'hl-bg-background',
  'bg-background/95': 'hl-bg-background-95',
  'bg-black/40': 'hl-bg-black-40',
  'bg-black/60': 'hl-bg-black-60',
  'bg-black/80': 'hl-bg-black-80',
  'bg-black/85': 'hl-bg-black-85',
  'bg-clip-text': 'hl-bg-clip-text',
  'bg-foreground': 'hl-bg-foreground',
  'bg-foreground/12': 'hl-bg-foreground-12',
  'bg-foreground/15': 'hl-bg-foreground-15',
  'bg-foreground/[0.06]': 'hl-bg-foreground-0-06',
  'bg-surface-panel/55': 'hl-bg-surface-panel-55',
  'bg-white/5': 'hl-bg-white-5',
  'blur-[4px]': 'hl-blur-4px',
  'border-[#6d8bff]/50': 'hl-border-6d8bff-50',
  'border-[color:var(--hero-glass-border)]': 'hl-border-color-var-hero-glass-border',
  'border-accent-500': 'hl-border-accent-500',
  'border-accent-500/12': 'hl-border-accent-500-12',
  'border-accent-500/14': 'hl-border-accent-500-14',
  'border-accent-500/20': 'hl-border-accent-500-20',
  'border-accent-500/35': 'hl-border-accent-500-35',
  'border-accent-500/45': 'hl-border-accent-500-45',
  'border-accent-500/50': 'hl-border-accent-500-50',
  'border-accent-500/55': 'hl-border-accent-500-55',
  'border-accent-500/85': 'hl-border-accent-500-85',
  'border-foreground/10': 'hl-border-foreground-10',
  'border-foreground/15': 'hl-border-foreground-15',
  'border-foreground/18': 'hl-border-foreground-18',
  'border-white/10': 'hl-border-white-10',
  'border-white/15': 'hl-border-white-15',
  'border-white/20': 'hl-border-white-20',
  'bottom-[14vh]': 'hl-bottom-14vh',
  'first:border-t-0': 'hl-first-border-t-0',
  'focus-visible:outline-2': 'hl-focus-visible-outline-2',
  'focus-visible:outline-foreground': 'hl-focus-visible-outline-foreground',
  'focus-visible:outline-offset-2': 'hl-focus-visible-outline-offset-2',
  'focus:bg-foreground/[0.1]': 'hl-focus-bg-foreground-0-1',
  'font-lato': 'hl-font-lato',
  'font-mulish': 'hl-font-mulish',
  'gap-[0.625rem]': 'hl-gap-0-625rem',
  'gap-[1.125rem]': 'hl-gap-1-125rem',
  'gap-[1.375rem]': 'hl-gap-1-375rem',
  'gap-[10px]': 'hl-gap-10px',
  'gap-[12px]': 'hl-gap-12px',
  'gap-[16px]': 'hl-gap-16px',
  'gap-[18px]': 'hl-gap-18px',
  'gap-[22px]': 'hl-gap-22px',
  'gap-[24px]': 'hl-gap-24px',
  'gap-[25px]': 'hl-gap-25px',
  'gap-[32px]': 'hl-gap-32px',
  'gap-[34vh]': 'hl-gap-34vh',
  'gap-[4px]': 'hl-gap-4px',
  'gap-[6px]': 'hl-gap-6px',
  'gap-[8px]': 'hl-gap-8px',
  'grid-cols-[2.75rem_1fr_auto]': 'hl-grid-cols-2-75rem_1fr_auto',
  'grid-cols-[minmax(0,1fr)_minmax(22rem,34rem)_minmax(0,1fr)]':
    'hl-grid-cols-minmax-0-1fr-_minmax-22rem-34rem-_minmax-0-1fr',
  'h-[1.5px]': 'hl-h-1-5px',
  'h-[124.97px]': 'hl-h-124-97px',
  'h-[18px]': 'hl-h-18px',
  'h-[43px]': 'hl-h-43px',
  'h-[44px]': 'hl-h-44px',
  'h-[800px]': 'hl-h-800px',
  'h-lvh': 'hl-h-lvh',
  'hover:bg-[#3a5cff]/30': 'hl-hover-bg-3a5cff-30',
  'hover:bg-foreground/5': 'hl-hover-bg-foreground-5',
  'hover:bg-white/10': 'hl-hover-bg-white-10',
  'hover:text-foreground/70': 'hl-hover-text-foreground-70',
  'inset-[-1px]': 'hl-inset-1px',
  'leading-[1.06]': 'hl-leading-1-06',
  'leading-[1.19]': 'hl-leading-1-19',
  'leading-[1.2]': 'hl-leading-1-2',
  'leading-[1.35]': 'hl-leading-1-35',
  'leading-[1.3]': 'hl-leading-1-3',
  'leading-[1.4]': 'hl-leading-1-4',
  'leading-none': 'hl-leading-none',
  'left-[32px]': 'hl-left-32px',
  'left-[389px]': 'hl-left-389px',
  'left-[3px]': 'hl-left-3px',
  'left-[409px]': 'hl-left-409px',
  'left-[509px]': 'hl-left-509px',
  'left-[50px]': 'hl-left-50px',
  'left-[518px]': 'hl-left-518px',
  'left-[658.46px]': 'hl-left-658-46px',
  'left-[990px]': 'hl-left-990px',
  'max-[1151px]:px-10': 'hl-max-1151px--px-10',
  'max-[360px]:pt-22.5': 'hl-max-360px--pt-22-5',
  'max-[360px]:px-0': 'hl-max-360px--px-0',
  'max-[360px]:py-[1.125rem]': 'hl-max-360px--py-1-125rem',
  'max-[360px]:text-[1.25rem]': 'hl-max-360px--text-1-25rem',
  'max-[376px]:pb-10': 'hl-max-376px--pb-10',
  'max-[376px]:pt-25': 'hl-max-376px--pt-25',
  'max-h-717:py-3': 'hl-max-h-717-py-3',
  'max-h-717:text-2xl': 'hl-max-h-717-text-2xl',
  'max-h-828:py-4': 'hl-max-h-828-py-4',
  'max-h-[calc(100dvh-1.5rem)]': "hl-max-h-calc-100dvh-1-5rem",
  'max-hero-lg:gap-x-8': 'hl-max-hero-lg-gap-x-8',
  'max-hero-lg:grid-cols-[minmax(0,1fr)_minmax(18rem,30rem)_minmax(0,1fr)]':
    'hl-max-hero-lg-grid-cols-minmax-0-1fr-_minmax-18rem-30rem-_minmax-0-1fr',
  'max-hero-md:flex-col': 'hl-max-hero-md-flex-col',
  'max-hero-md:gap-2.5': 'hl-max-hero-md-gap-2-5',
  'max-hero-md:gap-[1.375rem]': 'hl-max-hero-md-gap-1-375rem',
  'max-hero-md:gap-[1.875rem]': 'hl-max-hero-md-gap-1-875rem',
  'max-hero-md:items-start': 'hl-max-hero-md-items-start',
  'max-hero-md:leading-[1.2]': 'hl-max-hero-md-leading-1-2',
  'max-hero-md:max-w-[44ch]': 'hl-max-hero-md-max-w-44ch',
  'max-hero-md:mb-7': 'hl-max-hero-md-mb-7',
  'max-hero-md:mt-16': 'hl-max-hero-md-mt-16',
  'max-hero-md:mt-4': 'hl-max-hero-md-mt-4',
  'max-hero-md:mt-50': 'hl-max-hero-md-mt-50',
  'max-hero-md:mt-[10vh]': 'hl-max-hero-md-mt-10vh',
  'max-hero-md:pb-10': 'hl-max-hero-md-pb-10',
  'max-hero-md:pb-11': 'hl-max-hero-md-pb-11',
  'max-hero-md:pb-[7vh]': 'hl-max-hero-md-pb-7vh',
  'max-hero-md:pt-32': 'hl-max-hero-md-pt-32',
  'max-hero-md:pt-[2.25rem]': 'hl-max-hero-md-pt-2-25rem',
  'max-hero-md:pt-[3.25rem]': 'hl-max-hero-md-pt-3-25rem',
  'max-hero-md:py-[clamp(1rem,2.6vh,1.75rem)]':
    'hl-max-hero-md-py-clamp-1rem-2-6vh-1-75rem',
  'max-hero-md:text-2xl': 'hl-max-hero-md-text-2xl',
  'max-hero-md:text-[2rem]': 'hl-max-hero-md-text-2rem',
  'max-hero-md:text-[3rem]': 'hl-max-hero-md-text-3rem',
  'max-hero-md:text-[5rem]': 'hl-max-hero-md-text-5rem',
  'max-hero-md:text-left': 'hl-max-hero-md-text-left',
  'max-hero-md:text-sm': 'hl-max-hero-md-text-sm',
  'max-hero-md:top-[2.5rem]': 'hl-max-hero-md-top-2-5rem',
  'max-hero-xs:-ml-[0.3125rem]': 'hl-max-hero-xs--ml-0-3125rem',
  'max-hero-xs:-ml-[0.5rem]': 'hl-max-hero-xs--ml-0-5rem',
  'max-hero-xs:flex-col': 'hl-max-hero-xs-flex-col',
  'max-hero-xs:gap-3': 'hl-max-hero-xs-gap-3',
  'max-hero-xs:gap-4': 'hl-max-hero-xs-gap-4',
  'max-hero-xs:gap-5': 'hl-max-hero-xs-gap-5',
  'max-hero-xs:gap-[0.875rem]': 'hl-max-hero-xs-gap-0-875rem',
  'max-hero-xs:grid-cols-[2.25rem_1fr_auto]': 'hl-max-hero-xs-grid-cols-2-25rem_1fr_auto',
  'max-hero-xs:items-start': 'hl-max-hero-xs-items-start',
  'max-hero-xs:leading-[1.65]': 'hl-max-hero-xs-leading-1-65',
  'max-hero-xs:mb-6': 'hl-max-hero-xs-mb-6',
  'max-hero-xs:ml-3': 'hl-max-hero-xs-ml-3',
  'max-hero-xs:mt-12': 'hl-max-hero-xs-mt-12',
  'max-hero-xs:mt-3.5': 'hl-max-hero-xs-mt-3-5',
  'max-hero-xs:mt-35': 'hl-max-hero-xs-mt-35',
  'max-hero-xs:pb-9': 'hl-max-hero-xs-pb-9',
  'max-hero-xs:pb-[8vh]': 'hl-max-hero-xs-pb-8vh',
  'max-hero-xs:pl-[1.75rem]': 'hl-max-hero-xs-pl-1-75rem',
  'max-hero-xs:pt-24': 'hl-max-hero-xs-pt-24',
  'max-hero-xs:pt-28': 'hl-max-hero-xs-pt-28',
  'max-hero-xs:pt-[1.75rem]': 'hl-max-hero-xs-pt-1-75rem',
  'max-hero-xs:pt-[12vh]': 'hl-max-hero-xs-pt-12vh',
  'max-hero-xs:pt-[calc(1.125rem+env(safe-area-inset-top,0px))]':
    "hl-max-hero-xs-pt-calc-1-125rem-env-safe-area-inset-top-0px",
  'max-hero-xs:px-0.5': 'hl-max-hero-xs-px-0-5',
  'max-hero-xs:px-[1.375rem]': 'hl-max-hero-xs-px-1-375rem',
  'max-hero-xs:py-5': 'hl-max-hero-xs-py-5',
  'max-hero-xs:size-10': 'hl-max-hero-xs-size-10',
  'max-hero-xs:size-[1.875rem]': 'hl-max-hero-xs-size-1-875rem',
  'max-hero-xs:text-[0.625rem]': 'hl-max-hero-xs-text-0-625rem',
  'max-hero-xs:text-[0.6875rem]': 'hl-max-hero-xs-text-0-6875rem',
  'max-hero-xs:text-[0.71875rem]': 'hl-max-hero-xs-text-0-71875rem',
  'max-hero-xs:text-[0.8125rem]': 'hl-max-hero-xs-text-0-8125rem',
  'max-hero-xs:text-[0.84375rem]': 'hl-max-hero-xs-text-0-84375rem',
  'max-hero-xs:text-[0.9375rem]': 'hl-max-hero-xs-text-0-9375rem',
  'max-hero-xs:text-[1.0625rem]': 'hl-max-hero-xs-text-1-0625rem',
  'max-hero-xs:text-[1.375rem]': 'hl-max-hero-xs-text-1-375rem',
  'max-hero-xs:text-[1.625rem]': 'hl-max-hero-xs-text-1-625rem',
  'max-hero-xs:text-[1rem]': 'hl-max-hero-xs-text-1rem',
  'max-hero-xs:text-[2.5rem]': 'hl-max-hero-xs-text-2-5rem',
  'max-hero-xs:text-[3.5rem]': 'hl-max-hero-xs-text-3-5rem',
  'max-hero-xs:text-xl': 'hl-max-hero-xs-text-xl',
  'max-hero-xs:text-xs': 'hl-max-hero-xs-text-xs',
  'max-hero-xs:top-[2rem]': 'hl-max-hero-xs-top-2rem',
  'max-hero-xs:tracking-[0.32em]': 'hl-max-hero-xs-tracking-0-32em',
  'max-hero-xs:tracking-[0.3em]': 'hl-max-hero-xs-tracking-0-3em',
  'max-hero-xs:w-[0.625rem]': 'hl-max-hero-xs-w-0-625rem',
  'max-hero-xs:w-[1rem]': 'hl-max-hero-xs-w-1rem',
  'max-md:gap-[26vh]': 'hl-max-md-gap-26vh',
  'max-md:pl-[2.25rem]': 'hl-max-md-pl-2-25rem',
  'max-menu:block': 'hl-max-menu-block',
  'max-menu:hidden': 'hl-max-menu-hidden',
  'max-menu:pt-[calc(1.375rem+env(safe-area-inset-top,0px))]':
    "hl-max-menu-pt-calc-1-375rem-env-safe-area-inset-top-0px",
  'max-menu:size-[2.125rem]': 'hl-max-menu-size-2-125rem',
  'max-menu:text-[1.0625rem]': 'hl-max-menu-text-1-0625rem',
  'max-menu:tracking-[0.34em]': 'hl-max-menu-tracking-0-34em',
  'max-pad-sm:col-start-auto': 'hl-max-pad-sm-col-start-auto',
  'max-pad-sm:flex-row': 'hl-max-pad-sm-flex-row',
  'max-pad-sm:gap-4': 'hl-max-pad-sm-gap-4',
  'max-pad-sm:gap-x-0': 'hl-max-pad-sm-gap-x-0',
  'max-pad-sm:gap-y-8': 'hl-max-pad-sm-gap-y-8',
  'max-pad-sm:grid-cols-1': 'hl-max-pad-sm-grid-cols-1',
  'max-pad-sm:h-auto': 'hl-max-pad-sm-h-auto',
  'max-pad-sm:hidden': 'hl-max-pad-sm-hidden',
  'max-pad-sm:inline': 'hl-max-pad-sm-inline',
  'max-pad-sm:items-start': 'hl-max-pad-sm-items-start',
  'max-pad-sm:justify-start': 'hl-max-pad-sm-justify-start',
  'max-pad-sm:max-h-none': 'hl-max-pad-sm-max-h-none',
  'max-pad-sm:max-w-none': 'hl-max-pad-sm-max-w-none',
  'max-pad-sm:min-h-11': 'hl-max-pad-sm-min-h-11',
  'max-pad-sm:min-h-screen': 'hl-max-pad-sm-min-h-screen',
  'max-pad-sm:overflow-visible': 'hl-max-pad-sm-overflow-visible',
  'max-pad-sm:pb-0': 'hl-max-pad-sm-pb-0',
  'max-pad-sm:pb-14': 'hl-max-pad-sm-pb-14',
  'max-pad-sm:pt-0': 'hl-max-pad-sm-pt-0',
  'max-pad-sm:pt-30': 'hl-max-pad-sm-pt-30',
  'max-pad-sm:pt-[calc(1.875rem+env(safe-area-inset-top,0px))]':
    "hl-max-pad-sm-pt-calc-1-875rem-env-safe-area-inset-top-0px",
  'max-pad-sm:px-[1.875rem]': 'hl-max-pad-sm-px-1-875rem',
  'max-pad-sm:py-4': 'hl-max-pad-sm-py-4',
  'max-pad-sm:row-start-auto': 'hl-max-pad-sm-row-start-auto',
  'max-pad-sm:text-2xl': 'hl-max-pad-sm-text-2xl',
  'max-pad-sm:text-left': 'hl-max-pad-sm-text-left',
  'max-pad-sm:text-lg': 'hl-max-pad-sm-text-lg',
  'max-w-[18ch]': 'hl-max-w-18ch',
  'max-w-[20ch]': 'hl-max-w-20ch',
  'max-w-[30ch]': 'hl-max-w-30ch',
  'max-w-[32.5rem]': 'hl-max-w-32-5rem',
  'max-w-[34ch]': 'hl-max-w-34ch',
  'max-w-[400px]': 'hl-max-w-400px',
  'max-w-[420px]': 'hl-max-w-420px',
  'max-w-[53rem]': 'hl-max-w-53rem',
  'max-w-[54ch]': 'hl-max-w-54ch',
  'max-w-[560px]': 'hl-max-w-560px',
  'mb-[1.125rem]': 'hl-mb-1-125rem',
  'mb-[2.25rem]': 'hl-mb-2-25rem',
  'min-[913px]:hidden': 'hl-min-913px--hidden',
  'ml-[0.08em]': 'hl-ml-0-08em',
  'ml-[0.875rem]': 'hl-ml-0-875rem',
  'ml-[8px]': 'hl-ml-8px',
  'mt-75': 'hl-mt-75',
  'mt-[0.15em]': 'hl-mt-0-15em',
  'mt-[1.125rem]': 'hl-mt-1-125rem',
  'mt-[1.375rem]': 'hl-mt-1-375rem',
  'mt-[1.5rem]': 'hl-mt-1-5rem',
  'mt-[10px]': 'hl-mt-10px',
  'mt-[10vh]': 'hl-mt-10vh',
  'mt-[16px]': 'hl-mt-16px',
  'mt-[16vh]': 'hl-mt-16vh',
  'mt-[22px]': 'hl-mt-22px',
  'mt-[2px]': 'hl-mt-2px',
  'mt-[8px]': 'hl-mt-8px',
  'my-[6px]': 'hl-my-6px',
  'p-[10px]': 'hl-p-10px',
  'pb-[20px]': 'hl-pb-20px',
  'pb-[28px]': 'hl-pb-28px',
  'pb-[3.375rem]': 'hl-pb-3-375rem',
  'pb-[32px]': 'hl-pb-32px',
  'pb-[36px]': 'hl-pb-36px',
  'pb-[6px]': 'hl-pb-6px',
  'pb-[6vh]': 'hl-pb-6vh',
  'pb-[9vh]': 'hl-pb-9vh',
  'pl-[2px]': 'hl-pl-2px',
  'pl-[3.25rem]': 'hl-pl-3-25rem',
  'pl-[32px]': 'hl-pl-32px',
  'pl-[6px]': 'hl-pl-6px',
  'placeholder:text-foreground/70': 'hl-placeholder-text-foreground-70',
  'placeholder:text-foreground/90': 'hl-placeholder-text-foreground-90',
  'pr-[24px]': 'hl-pr-24px',
  'pr-[28px]': 'hl-pr-28px',
  'pr-[2px]': 'hl-pr-2px',
  'pt-[1.875rem]': 'hl-pt-1-875rem',
  'pt-[100px]': 'hl-pt-100px',
  'pt-[16px]': 'hl-pt-16px',
  'pt-[16vh]': 'hl-pt-16vh',
  'pt-[3rem]': 'hl-pt-3rem',
  'pt-[4rem]': 'hl-pt-4rem',
  'pt-[6px]': 'hl-pt-6px',
  'pt-[7.5rem]': 'hl-pt-7-5rem',
  'pt-[92px]': 'hl-pt-92px',
  'pt-[96px]': 'hl-pt-96px',
  'pt-[calc(2.8125rem+env(safe-area-inset-top,0px))]':
    "hl-pt-calc-2-8125rem-env-safe-area-inset-top-0px",
  'px-6.5': 'hl-px-6-5',
  'px-[1.375rem]': 'hl-px-1-375rem',
  'px-[1.625rem]': 'hl-px-1-625rem',
  'px-[10px]': 'hl-px-10px',
  'px-[16px]': 'hl-px-16px',
  'px-[18px]': 'hl-px-18px',
  'px-[20px]': 'hl-px-20px',
  'px-[24px]': 'hl-px-24px',
  'px-[28px]': 'hl-px-28px',
  'px-[32px]': 'hl-px-32px',
  'px-[5.125rem]': 'hl-px-5-125rem',
  'py-[0.6875rem]': 'hl-py-0-6875rem',
  'py-[0.9375rem]': 'hl-py-0-9375rem',
  'py-[1.375rem]': 'hl-py-1-375rem',
  'py-[12px]': 'hl-py-12px',
  'py-[13px]': 'hl-py-13px',
  'py-[14px]': 'hl-py-14px',
  'py-[16px]': 'hl-py-16px',
  'py-[2px]': 'hl-py-2px',
  'py-[6px]': 'hl-py-6px',
  'py-[clamp(1.125rem,3vh,2rem)]': 'hl-py-clamp-1-125rem-3vh-2rem',
  'ring-1': 'hl-ring-1',
  rounded: 'hl-rounded',
  'rounded-[10px]': 'hl-rounded-10px',
  'rounded-[16px]': 'hl-rounded-16px',
  'rounded-[24px]': 'hl-rounded-24px',
  'rounded-[2px]': 'hl-rounded-2px',
  'rounded-[32px]': 'hl-rounded-32px',
  'rounded-[50px]': 'hl-rounded-50px',
  'rounded-[6.25rem]': 'hl-rounded-6-25rem',
  shadow: 'hl-shadow',
  'shadow-[var(--shadow-loader-rail)]': 'hl-shadow-var-shadow-loader-rail',
  'shadow-cta': 'hl-shadow-cta',
  'shadow-cta-hover': 'hl-shadow-cta-hover',
  'size-[0.4375rem]': 'hl-size-0-4375rem',
  'size-[150px]': 'hl-size-150px',
  'size-[188px]': 'hl-size-188px',
  'size-[18px]': 'hl-size-18px',
  'size-[19px]': 'hl-size-19px',
  'size-[210px]': 'hl-size-210px',
  'size-[23px]': 'hl-size-23px',
  'size-[285px]': 'hl-size-285px',
  'size-[39px]': 'hl-size-39px',
  'size-[3px]': 'hl-size-3px',
  'size-[44px]': 'hl-size-44px',
  'size-[92px]': 'hl-size-92px',
  'sm:w-[420px]': 'hl-sm-w-420px',
  'text-[0.42em]': 'hl-text-0-42em',
  'text-[0.6875rem]': 'hl-text-0-6875rem',
  'text-[0.6875rem]/none': 'hl-text-0-6875rem-none',
  'text-[0.75rem]': 'hl-text-0-75rem',
  'text-[0.75rem]/[1.5]': 'hl-text-0-75rem-1-5',
  'text-[0.8125rem]/[1.6]': 'hl-text-0-8125rem-1-6',
  'text-[0.875rem]': 'hl-text-0-875rem',
  'text-[0.9375rem]/[1.6]': 'hl-text-0-9375rem-1-6',
  'text-[1.125rem]': 'hl-text-1-125rem',
  'text-[1.375rem]/[1.15]': 'hl-text-1-375rem-1-15',
  'text-[1.625rem]': 'hl-text-1-625rem',
  'text-[1.75rem]': 'hl-text-1-75rem',
  'text-[1.75rem]/[1.3]': 'hl-text-1-75rem-1-3',
  'text-[10px]': 'hl-text-10px',
  'text-[11px]': 'hl-text-11px',
  'text-[14px]': 'hl-text-14px',
  'text-[15px]': 'hl-text-15px',
  'text-[16px]': 'hl-text-16px',
  'text-[17px]': 'hl-text-17px',
  'text-[18px]': 'hl-text-18px',
  'text-[2.875rem]/[1.18]': 'hl-text-2-875rem-1-18',
  'text-[22px]': 'hl-text-22px',
  'text-[3.75rem]/[0.95]': 'hl-text-3-75rem-0-95',
  'text-[32px]': 'hl-text-32px',
  'text-[56px]': 'hl-text-56px',
  'text-[7rem]/[0.8]': 'hl-text-7rem-0-8',
  'text-[clamp(2.875rem,7vw,5.75rem)]/[0.9]': 'hl-text-clamp-2-875rem-7vw-5-75rem-0-9',
  'text-[clamp(24px,6.4vw,44px)]': 'hl-text-clamp-24px-6-4vw-44px',
  'text-accent-300': 'hl-text-accent-300',
  'text-accent-300/70': 'hl-text-accent-300-70',
  'text-accent-500': 'hl-text-accent-500',
  'text-accent-500/15': 'hl-text-accent-500-15',
  'text-accent-500/55': 'hl-text-accent-500-55',
  'text-accent-500/85': 'hl-text-accent-500-85',
  'text-accent-500/95': 'hl-text-accent-500-95',
  'text-background': 'hl-text-background',
  'text-foreground': 'hl-text-foreground',
  'text-foreground/38': 'hl-text-foreground-38',
  'text-foreground/42': 'hl-text-foreground-42',
  'text-foreground/45': 'hl-text-foreground-45',
  'text-foreground/56': 'hl-text-foreground-56',
  'text-foreground/60': 'hl-text-foreground-60',
  'text-foreground/70': 'hl-text-foreground-70',
  'text-foreground/72': 'hl-text-foreground-72',
  'text-foreground/80': 'hl-text-foreground-80',
  'text-foreground/85': 'hl-text-foreground-85',
}

/**
 * Le vocabulaire du gabarit.
 *
 * `page-gutter` etait une directive `@utility`, `scene-overlay` une classe de
 * `@layer components` ; toutes deux sont desormais des regles ordinaires de la
 * feuille. `scroll-layout` et `scroll-layout-content` ne peignent rien : ce
 * sont des reperes de structure.
 */
export const UNCHANGED = new Set([
  'group',
  'page-gutter',
  'scene-overlay',
  'scroll-layout',
  'scroll-layout-content',
])

/**
 * Les valeurs qu une expression compare, et qui ne sont pas des classes.
 *
 * La scene place ses corps `left`, `right`, `around` ou `core` : ce sont des
 * positions, pas des utilitaires.
 */
export const IGNORED = new Set(['left', 'right', 'center', 'around', 'core', 'the'])

/** Des mots croises ailleurs, qui ressemblent a une classe sans en etre. */
export const FAUX_AMIS = new Set([
  /*
   * Des identifiants de section, pas des classes : `screens.ts` les emploie
   * comme ancres de defilement.
   */
  'product-0',
  'product-1',
  'roadmap-0',
  'roadmap-1',
  'roadmap-2',

  'hidden',
  'resize',
  'fixed',
  'relative',
  'absolute',
  // Un mot de phrase, croise dans un commentaire.
  'the',
  'natively,',
  'so',
  // Des valeurs de propriete, ecrites dans un objet de style.
  'block',
  'static',
])

/** Les utilitaires que les deux moteurs n epellent pas pareil. */
export const RESPELLED = {
  border: 'o-border-w-1',
}
