/**
 * La table de `joaillier`.
 *
 * Les renommages sont derives du bloc de jetons de la feuille par
 * `scripts/derive-template-classes.mjs` ; ce qui suit est ce qu il ne peut pas
 * deviner.
 */

export const RENAMED = {
  /*
   * Des variantes que le systeme connait, et qu on fait deriver quand meme.
   *
   * Nos regles derivees repetent leur classe et pesent deux fois plus qu un
   * utilitaire. La ou l original comptait sur l ordre entre deux utilitaires de
   * meme poids, la derivee gagnait partout : la plaque du hero gardait son
   * `left` de bureau sur un telephone, a 1338 px du bord. Les deriver toutes
   * les deux leur rend le meme poids, et l ordre tranche comme avant.
   */

  /*
   * Deux homonymes. Notre systeme connait `o-font-sans` et `o-ease-entrance`,
   * et n entend pas la meme chose : ici la sans-serif est l Inter Tight, et la
   * courbe est celle du gabarit.
   */
  "disabled:cursor-wait": "jo-disabled-cursor-wait",
  "disabled:opacity-70": "jo-disabled-opacity-70",
  "hover:opacity-90": "jo-hover-opacity-90",
  "lg:fixed": "jo-lg-fixed",
  "max-lg:bottom-auto": "jo-max-lg-bottom-auto",
  "max-lg:col-span-12": "jo-max-lg-col-span-12",
  "max-lg:col-start-1": "jo-max-lg-col-start-1",
  "max-lg:grid-cols-1": "jo-max-lg-grid-cols-1",
  "max-lg:hidden": "jo-max-lg-hidden",
  "max-lg:items-end": "jo-max-lg-items-end",
  "max-lg:items-start": "jo-max-lg-items-start",
  "max-lg:left-0": "jo-max-lg-left-0",
  "max-lg:left-1/2": "jo-max-lg-left-1-2",
  "max-lg:left-auto": "jo-max-lg-left-auto",
  "max-lg:mx-auto": "jo-max-lg-mx-auto",
  "max-lg:order-1": "jo-max-lg-order-1",
  "max-lg:right-0": "jo-max-lg-right-0",
  "max-lg:text-center": "jo-max-lg-text-center",
  "max-lg:text-left": "jo-max-lg-text-left",
  "max-lg:text-right": "jo-max-lg-text-right",
  "max-lg:top-auto": "jo-max-lg-top-auto",
  "max-lg:w-auto": "jo-max-lg-w-auto",
  "max-lg:w-fit": "jo-max-lg-w-fit",
  "max-md:border-b": "jo-max-md-border-b",
  "max-md:flex-col": "jo-max-md-flex-col",
  "max-md:grid-cols-1": "jo-max-md-grid-cols-1",
  "max-md:hidden": "jo-max-md-hidden",
  "max-md:items-stretch": "jo-max-md-items-stretch",
  "max-md:left-0": "jo-max-md-left-0",
  "max-md:mx-auto": "jo-max-md-mx-auto",
  "max-md:right-0": "jo-max-md-right-0",
  "sm:bottom-12": "jo-sm-bottom-12",
  "sm:left-auto": "jo-sm-left-auto",
  "sm:p-6": "jo-sm-p-6",
  "sm:p-7": "jo-sm-p-7",
  "sm:right-12": "jo-sm-right-12",
  "bg-action-inverse": "jo-bg-action-inverse",
  "border-line-strong": "jo-border-line-strong",
  "focus-visible:outline-foreground-ink": "jo-focus-visible-outline-foreground-ink",
  "text-action-inverse-ink": "jo-text-action-inverse-ink",
  "h-[19.6875rem]": "jo-h-19-6875rem",
  "left-[29.375rem]": "jo-left-29-375rem",
  "left-[77.1875rem]": "jo-left-77-1875rem",
  "lg:z-50": "jo-lg-z-50",
  "max-lg:bottom-page": "jo-max-lg-bottom-page",
  "max-lg:h-[calc(min(100vw-3rem,78vw,(100vh-36rem)/0.63)*0.63)]": "jo-max-lg-h-calc-min-100vw-3rem-78vw-100vh-36rem-0-63-0-63",
  "max-lg:top-[calc(50%+min(100vw-3rem,78vw,(100vh-36rem)/0.63)*0.315+12px)]": "jo-max-lg-top-calc-50-min-100vw-3rem-78vw-100vh-36rem-0-63-0-315-12px",
  "max-lg:top-[calc(50%+min(100vw-3rem,78vw,(100vh-36rem)/0.63)*0.315+5.75rem)]": "jo-max-lg-top-calc-50-min-100vw-3rem-78vw-100vh-36rem-0-63-0-315-5-75rem",
  "max-lg:top-[calc(50%-min(100vw-3rem,78vw,(100vh-36rem)/0.63)*0.315)]": "jo-max-lg-top-calc-50-min-100vw-3rem-78vw-100vh-36rem-0-63-0-315",
  "max-lg:top-[calc(50%-min(100vw-3rem,78vw,(100vh-36rem)/0.63)*0.315-23.2px)]": "jo-max-lg-top-calc-50-min-100vw-3rem-78vw-100vh-36rem-0-63-0-315-23-2px",
  "max-lg:top-[calc(50%-min(100vw-3rem,78vw,(100vh-36rem)/0.63)*0.315-9.5rem)]": "jo-max-lg-top-calc-50-min-100vw-3rem-78vw-100vh-36rem-0-63-0-315-9-5rem",
  "max-lg:w-[min(100vw-3rem,78vw,(100vh-36rem)/0.63)]": "jo-max-lg-w-min-100vw-3rem-78vw-100vh-36rem-0-63",
  "max-md:bottom-[calc(24px+env(safe-area-inset-bottom))]": "jo-max-md-bottom-calc-24px-env-safe-area-inset-bottom",
  "max-md:h-[calc(min(100vw-3rem,(100vh-30rem)/0.63)*0.63)]": "jo-max-md-h-calc-min-100vw-3rem-100vh-30rem-0-63-0-63",
  "max-md:top-[calc(50%+min(100vw-3rem,(100vh-30rem)/0.63)*0.315+12px)]": "jo-max-md-top-calc-50-min-100vw-3rem-100vh-30rem-0-63-0-315-12px",
  "max-md:top-[calc(50%+min(100vw-3rem,(100vh-30rem)/0.63)*0.315+69px)]": "jo-max-md-top-calc-50-min-100vw-3rem-100vh-30rem-0-63-0-315-69px",
  "max-md:top-[calc(50%-min(100vw-3rem,(100vh-30rem)/0.63)*0.315)]": "jo-max-md-top-calc-50-min-100vw-3rem-100vh-30rem-0-63-0-315",
  "max-md:top-[calc(50%-min(100vw-3rem,(100vh-30rem)/0.63)*0.315-23.2px)]": "jo-max-md-top-calc-50-min-100vw-3rem-100vh-30rem-0-63-0-315-23-2px",
  "max-md:top-[calc(50%-min(100vw-3rem,(100vh-30rem)/0.63)*0.315-87px)]": "jo-max-md-top-calc-50-min-100vw-3rem-100vh-30rem-0-63-0-315-87px",
  "max-md:w-[min(100vw-3rem,(100vh-30rem)/0.63)]": "jo-max-md-w-min-100vw-3rem-100vh-30rem-0-63",
  "right-[62.125rem]": "jo-right-62-125rem",
  "top-[calc(50%+10.59375rem)]": "jo-top-calc-50-10-59375rem",
  "top-[calc(50%-11.15625rem)]": "jo-top-calc-50-11-15625rem",
  "top-[calc(50%-4.3125rem)]": "jo-top-calc-50-4-3125rem",
  "top-[calc(50%-9.84375rem)]": "jo-top-calc-50-9-84375rem",
  "w-[11.3125rem]": "jo-w-11-3125rem",
  "w-[14.875rem]": "jo-w-14-875rem",
  "w-[21.258625rem]": "jo-w-21-258625rem",
  "w-[31.25rem]": "jo-w-31-25rem",
  "-translate-x-1/2": "jo--translate-x-1-2",
  "-translate-y-1/2": "jo--translate-y-1-2",
  "bg-foreground-signal": "jo-bg-foreground-signal",
  "bg-scrim-page": "jo-bg-scrim-page",
  "h-[8.25rem]": "jo-h-8-25rem",
  "h-[8.3125rem]": "jo-h-8-3125rem",
  "left-[1rem]": "jo-left-1rem",
  "left-[37.9375rem]": "jo-left-37-9375rem",
  "left-[62.125rem]": "jo-left-62-125rem",
  "max-lg:-ml-[7rem]": "jo-max-lg-ml-7rem",
  "max-lg:h-[8.1rem]": "jo-max-lg-h-8-1rem",
  "max-lg:leading-[44.8px]": "jo-max-lg-leading-44-8px",
  "max-lg:left-[12px]": "jo-max-lg-left-12px",
  "max-lg:left-page": "jo-max-lg-left-page",
  "max-lg:right-page": "jo-max-lg-right-page",
  "max-lg:size-[20px]": "jo-max-lg-size-20px",
  "max-lg:size-[7px]": "jo-max-lg-size-7px",
  "max-lg:text-[56px]": "jo-max-lg-text-56px",
  "max-lg:top-[12px]": "jo-max-lg-top-12px",
  "max-lg:top-page": "jo-max-lg-top-page",
  "max-lg:w-[14rem]": "jo-max-lg-w-14rem",
  "max-md:leading-[16.2px]": "jo-max-md-leading-16-2px",
  "max-md:leading-[33.6px]": "jo-max-md-leading-33-6px",
  "max-md:text-[18px]": "jo-max-md-text-18px",
  "max-md:text-[42px]": "jo-max-md-text-42px",
  "size-[0.5rem]": "jo-size-0-5rem",
  "size-[1.5rem]": "jo-size-1-5rem",
  "top-[1rem]": "jo-top-1rem",
  "w-[14.1875rem]": "jo-w-14-1875rem",
  "w-[5.75rem]": "jo-w-5-75rem",
  "font-sans": "jo-font-sans",
  "ease-entrance": "jo-ease-entrance",
  "rounded-b-media": "jo-rounded-b-media",
  "rounded-t-media": "jo-rounded-t-media",
  "-bottom-1": "jo--bottom-1",
  "-bottom-px": "jo--bottom-px",
  "-inset-[6rem]": "jo--inset-6rem",
  "-mt-[0.35em]": "jo--mt-0-35em",
  "[mix-blend-mode:overlay]": "jo--mix-blend-mode-overlay",
  "aspect-[3/4]": "jo-aspect-3-4",
  "aspect-[4/5]": "jo-aspect-4-5",
  "bg-action-primary": "jo-bg-action-primary",
  "bg-background": "jo-bg-background",
  "bg-background/95": "jo-bg-background-95",
  "bg-black/40": "jo-bg-black-40",
  "bg-foreground": "jo-bg-foreground",
  "bg-foreground-accent": "jo-bg-foreground-accent",
  "bg-foreground-accent-muted": "jo-bg-foreground-accent-muted",
  "bg-foreground/15": "jo-bg-foreground-15",
  "bg-line": "jo-bg-line",
  "bg-line-ink": "jo-bg-line-ink",
  "bg-line-strong": "jo-bg-line-strong",
  "bg-linear-to-t": "jo-bg-linear-to-t",
  "bg-scrim-media": "jo-bg-scrim-media",
  "bg-scrim-scene": "jo-bg-scrim-scene",
  "bg-surface-band": "jo-bg-surface-band",
  "bg-surface-card": "jo-bg-surface-card",
  "bg-surface-cinema": "jo-bg-surface-cinema",
  "bg-surface-glass": "jo-bg-surface-glass",
  "border-foreground-accent": "jo-border-foreground-accent",
  "border-foreground-accent-muted": "jo-border-foreground-accent-muted",
  "border-foreground/10": "jo-border-foreground-10",
  "border-foreground/15": "jo-border-foreground-15",
  "border-line": "jo-border-line",
  "bottom-md": "jo-bottom-md",
  "bottom-page": "jo-bottom-page",
  "col-start-8": "jo-col-start-8",
  "col-start-9": "jo-col-start-9",
  "duration-[var(--duration-fast)]": "jo-duration-var-duration-fast",
  "focus-visible:outline-2": "jo-focus-visible-outline-2",
  "focus-visible:outline-foreground": "jo-focus-visible-outline-foreground",
  "focus-visible:outline-foreground-accent": "jo-focus-visible-outline-foreground-accent",
  "focus-visible:outline-offset-2": "jo-focus-visible-outline-offset-2",
  "focus-visible:outline-offset-4": "jo-focus-visible-outline-offset-4",
  "focus-visible:placeholder:text-foreground-accent-soft": "jo-focus-visible-placeholder-text-foreground-accent-soft",
  "focus-visible:text-foreground-accent": "jo-focus-visible-text-foreground-accent",
  "font-display": "jo-font-display",
  "font-ui": "jo-font-ui",
  "from-scrim-panel": "jo-from-scrim-panel",
  "gap-lg": "jo-gap-lg",
  "gap-md": "jo-gap-md",
  "gap-sm": "jo-gap-sm",
  "gap-x-lg": "jo-gap-x-lg",
  "gap-xs": "jo-gap-xs",
  "gap-y-lg": "jo-gap-y-lg",
  "gap-y-stack": "jo-gap-y-stack",
  "gap-y-xl": "jo-gap-y-xl",
  "group-focus-visible:scale-x-100": "jo-group-focus-visible-scale-x-100",
  "group-hover:border-foreground-accent": "jo-group-hover-border-foreground-accent",
  "group-hover:scale-x-100": "jo-group-hover-scale-x-100",
  "group-hover:text-foreground-accent": "jo-group-hover-text-foreground-accent",
  "group-hover:translate-x-[3px]": "jo-group-hover-translate-x-3px",
  "h-2/5": "jo-h-2-5",
  "h-[18px]": "jo-h-18px",
  "hover:bg-foreground-accent": "jo-hover-bg-foreground-accent",
  "hover:bg-foreground/5": "jo-hover-bg-foreground-5",
  "hover:text-foreground-accent": "jo-hover-text-foreground-accent",
  "hover:text-foreground/70": "jo-hover-text-foreground-70",
  "leading-[0.85]": "jo-leading-0-85",
  "leading-body": "jo-leading-body",
  "leading-caption": "jo-leading-caption",
  "leading-copy": "jo-leading-copy",
  "leading-heading": "jo-leading-heading",
  "leading-headline": "jo-leading-headline",
  "leading-lead": "jo-leading-lead",
  "leading-none": "jo-leading-none",
  "leading-statement": "jo-leading-statement",
  "leading-title": "jo-leading-title",
  "leading-wordmark": "jo-leading-wordmark",
  "left-[3px]": "jo-left-3px",
  "left-md": "jo-left-md",
  "left-page": "jo-left-page",
  "left-xl": "jo-left-xl",
  "max-h-[calc(100dvh-1.5rem)]": "jo-max-h-calc-100dvh-1-5rem",
  "max-lg:gap-[10.8px]": "jo-max-lg-gap-10-8px",
  "max-lg:gap-xl": "jo-max-lg-gap-xl",
  "max-lg:leading-[11.2px]": "jo-max-lg-leading-11-2px",
  "max-lg:leading-[18px]": "jo-max-lg-leading-18px",
  "max-lg:leading-[57.6px]": "jo-max-lg-leading-57-6px",
  "max-lg:mt-[21px]": "jo-max-lg-mt-21px",
  "max-lg:text-[14px]": "jo-max-lg-text-14px",
  "max-lg:text-[20px]": "jo-max-lg-text-20px",
  "max-lg:text-[72px]": "jo-max-lg-text-72px",
  "max-md:border-line": "jo-max-md-border-line",
  "max-md:gap-md": "jo-max-md-gap-md",
  "max-md:gap-xl": "jo-max-md-gap-xl",
  "max-md:leading-[26px]": "jo-max-md-leading-26px",
  "max-md:leading-[36px]": "jo-max-md-leading-36px",
  "max-md:leading-[40px]": "jo-max-md-leading-40px",
  "max-md:leading-[44.8px]": "jo-max-md-leading-44-8px",
  "max-md:p-lg": "jo-max-md-p-lg",
  "max-md:pb-page": "jo-max-md-pb-page",
  "max-md:pt-[29px]": "jo-max-md-pt-29px",
  "max-md:py-stack": "jo-max-md-py-stack",
  "max-md:rounded-media": "jo-max-md-rounded-media",
  "max-md:text-[20px]": "jo-max-md-text-20px",
  "max-md:text-[24vw]": "jo-max-md-text-24vw",
  "max-md:text-[28px]": "jo-max-md-text-28px",
  "max-md:text-[40px]": "jo-max-md-text-40px",
  "max-md:text-[56px]": "jo-max-md-text-56px",
  "max-w-[22rem]": "jo-max-w-22rem",
  "max-w-[28rem]": "jo-max-w-28rem",
  "max-w-[34rem]": "jo-max-w-34rem",
  "max-w-[36rem]": "jo-max-w-36rem",
  "max-w-[40rem]": "jo-max-w-40rem",
  "max-w-[44rem]": "jo-max-w-44rem",
  "max-w-[52rem]": "jo-max-w-52rem",
  "max-w-[560px]": "jo-max-w-560px",
  "mt-lg": "jo-mt-lg",
  "mt-md": "jo-mt-md",
  "mt-stack": "jo-mt-stack",
  "mt-xl": "jo-mt-xl",
  "mt-xs": "jo-mt-xs",
  "p-xl": "jo-p-xl",
  "p-xs": "jo-p-xs",
  "pb-page": "jo-pb-page",
  "pb-stack": "jo-pb-stack",
  "pb-xs": "jo-pb-xs",
  "pl-xl": "jo-pl-xl",
  "placeholder:text-foreground-accent-muted": "jo-placeholder-text-foreground-accent-muted",
  "pt-section": "jo-pt-section",
  "pt-stack": "jo-pt-stack",
  "px-md": "jo-px-md",
  "px-page": "jo-px-page",
  "px-xl": "jo-px-xl",
  "py-lg": "jo-py-lg",
  "py-md": "jo-py-md",
  "py-section": "jo-py-section",
  "py-sm": "jo-py-sm",
  "py-stack": "jo-py-stack",
  "right-md": "jo-right-md",
  "right-page": "jo-right-page",
  "rounded-[10px]": "jo-rounded-10px",
  "rounded-media": "jo-rounded-media",
  "rounded-pill": "jo-rounded-pill",
  "scale-x-0": "jo-scale-x-0",
  "shadow": "jo-shadow",
  "size-[1rem]": "jo-size-1rem",
  "sm:w-[420px]": "jo-sm-w-420px",
  "text-[12vw]": "jo-text-12vw",
  "text-action-primary-ink": "jo-text-action-primary-ink",
  "text-background": "jo-text-background",
  "text-body": "jo-text-body",
  "text-caption": "jo-text-caption",
  "text-display": "jo-text-display",
  "text-foreground": "jo-text-foreground",
  "text-foreground-accent": "jo-text-foreground-accent",
  "text-foreground-accent-muted": "jo-text-foreground-accent-muted",
  "text-foreground-accent-soft": "jo-text-foreground-accent-soft",
  "text-foreground-accent-strong": "jo-text-foreground-accent-strong",
  "text-foreground-accent/20": "jo-text-foreground-accent-20",
  "text-foreground-ink": "jo-text-foreground-ink",
  "text-foreground-ink-muted": "jo-text-foreground-ink-muted",
  "text-foreground-silver": "jo-text-foreground-silver",
  "text-foreground/60": "jo-text-foreground-60",
  "text-foreground/70": "jo-text-foreground-70",
  "text-headline": "jo-text-headline",
  "text-lead": "jo-text-lead",
  "text-statement": "jo-text-statement",
  "text-title": "jo-text-title",
  "text-wordmark": "jo-text-wordmark",
  "top-[3px]": "jo-top-3px",
  "top-md": "jo-top-md",
  "top-page": "jo-top-page",
  "top-xl": "jo-top-xl",
  "tracking-[0.08em]": "jo-tracking-0-08em",
  "tracking-[0.12em]": "jo-tracking-0-12em",
  "tracking-[0.14em]": "jo-tracking-0-14em",
  "w-[18px]": "jo-w-18px",
  "w-[2rem]": "jo-w-2rem",
  "w-[calc(100vw-1.5rem)]": "jo-w-calc-100vw-1-5rem",
  "z-[100]": "jo-z-100",
}

export const UNCHANGED = new Set([
  /*
   * `group` n a pas de regle a lui : c est la marque que les selecteurs
   * `.group:hover .x` vont chercher. Les deux autres sont les prises auxquelles
   * le defilement doux s accroche depuis le script.
   */
  'group',
  /*
   * Quatre classes que le gabarit se donne par `@utility` dans sa feuille :
   * les prefixer reviendrait a les effacer.
   */
  'text-trim',
  'h-viewport',
  'min-h-viewport',
  'pull-viewport',
  'scroll-layout',
  'scroll-layout-content',
])

export const FAUX_AMIS = new Set([
  // Le membre d un type : `tone?: "cream" | "ink"`.
  'ink',
  /*
   * Des valeurs CSS ecrites en clair, un nom d evenement, et de la prose de
   * commentaire — `hero.geometry.ts` explique chacune de ses classes. Verifies
   * un a un.
   */
  'absolute',
  'fixed',
  'flex',
  'hidden',
  'inline-block',
  'items-center',
  'object-cover',
  'pointer-events-none',
  'relative',
  'sticky',
  'visible',
  'resize',
  'block',
  'contents',
  'grid',
  'text-right',
  'min-w-0',
  'shrink-0',
  'underline',
  'whitespace-nowrap',
  'z-10',
  'z-50',
])

export const IGNORED = new Set(FAUX_AMIS)

export const RESPELLED = { border: 'o-border-w-1' }
