/**
 * Grain: a static film noise, generated by an SVG filter.
 *
 * ## Why an SVG in a data URI rather than a canvas
 *
 * The noise is produced by `feTurbulence`, a generator the browser already
 * ships: the component merely describes the filter in an SVG encoded as a data
 * URI and lays it down as a background image. Nothing runs after the first
 * render — no canvas to fill pixel by pixel, no loop, no graphics context to
 * reserve.
 *
 * ## Why the grain is monochrome by default
 *
 * `feTurbulence` produces a coloured noise, where each channel draws its own
 * value. On an interface, those coloured confetti are noticeable; a desaturated
 * grain reads as a matter, not as a pattern. A zero-saturation matrix
 * neutralises it, and a switch gives the coloured version back to whoever wants
 * it.
 *
 * @module
 */

import { mergePresentation, type Customisable } from '@odoro-cli/engine'
import { type CSSProperties, type ReactElement } from 'react'

/** Props specific to this component. */
export interface NoiseOwnProps {
  /** Opacity of the grain, between 0 and 1. @defaultValue 0.1 */
  opacity?: number
  /** Base frequency of the noise. Higher is finer. @defaultValue 0.8 */
  scale?: number
  /** Desaturates the grain. @defaultValue true */
  monochrome?: boolean
}

/** All props. */
export type NoiseProps = Customisable<NoiseOwnProps>

/**
 * Background grain.
 *
 * @example
 * <div className="o-relative o-min-h-screen">
 *   <Noise className="o-absolute o-inset-0" opacity={0.08} />
 *   <main className="o-relative">…</main>
 * </div>
 */
export function Noise({
  opacity = 0.1,
  scale = 0.8,
  monochrome = true,
  ...rest
}: NoiseProps): ReactElement {
  // The SVG is rebuilt when a setting changes: it is a string, not a document,
  // and the browser caches the image by URI.
  const svg = [
    '<svg xmlns="http://www.w3.org/2000/svg" width="180" height="180">',
    '<filter id="grain">',
    `<feTurbulence type="fractalNoise" baseFrequency="${String(scale)}" numOctaves="2" stitchTiles="stitch"/>`,
    monochrome ? '<feColorMatrix type="saturate" values="0"/>' : '',
    '</filter>',
    '<rect width="100%" height="100%" filter="url(#grain)"/>',
    '</svg>',
  ].join('')

  const { className, style } = mergePresentation({}, rest)

  return (
    <div
      {...rest}
      className={className}
      style={
        {
          ...style,
          opacity,
          backgroundImage: `url("data:image/svg+xml,${encodeURIComponent(svg)}")`,
        } as CSSProperties
      }
      aria-hidden
    />
  )
}
